name: Node.js CI

on:
  push:
    branches: [ "main" , "dev" ]
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    name: Use Node.js ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup node
    - uses: pnpm/action-setup@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
    
